### ISSUE TITLE
Fix  bsc api

### ISSUE THREAD

**Issue by CruiseMan** [CreamFi/cream-docs#3]
Could not find better place to report api issue, so
https://api.cream.finance/api/v1/rates?block_number=8761313&comptroller=bsc
from docs https://api.cream.finance/api/documentations/#/Ethereum/CTokenController_rates
<img width="958" alt="Screen Shot 2021-06-30 at 4 53 07 PM" src="https://user-images.githubusercontent.com/15807643/124045027-a715b580-d9c3-11eb-9bf4-e3028e1f9f51.png">

APi basically is down
https://www.host-tracker.com/v3/en/check/2/0639655c-fed9-eb11-b35f-00155d455476

**Comment by eason1305** [comment]
Thanks for pointing this out, but for now Rates API only supports Ethereum.
